# Generated by Django 3.2.6 on 2021-08-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counseling',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='상담완료 여부'),
        ),
        migrations.AlterField(
            model_name='counseling',
            name='information',
            field=models.TextField(verbose_name='어르신 상태'),
        ),
        migrations.AlterField(
            model_name='counseling',
            name='name',
            field=models.CharField(max_length=30, verbose_name='신청자 이름'),
        ),
        migrations.AlterField(
            model_name='counseling',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='counseling',
            name='relation',
            field=models.CharField(max_length=20, verbose_name='어르신과의 관계'),
        ),
    ]
